import faulthandler
faulthandler.enable()
print("start", flush=True)
import torch; print("torch", torch.__version__, "cuda", torch.cuda.is_available(), flush=True)
import numpy; print("numpy", numpy.__version__, flush=True)
import soundfile; print("soundfile ok", flush=True)
from datasets import Dataset; print("datasets ok", flush=True)
from transformers import WhisperProcessor, WhisperForConditionalGeneration; print("transformers ok", flush=True)
from peft import LoraConfig, get_peft_model; print("peft ok", flush=True)
print("loading processor", flush=True)
proc = WhisperProcessor.from_pretrained("openai/whisper-small")
print("processor ok", flush=True)
print("loading model", flush=True)
m = WhisperForConditionalGeneration.from_pretrained("openai/whisper-small")
print("model ok", flush=True)
print("to cuda", flush=True)
m = m.to("cuda")
print("cuda ok, params:", sum(p.numel() for p in m.parameters()), flush=True)
